icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#2f343f"
idle_fg = "#f3f4f5"

info_bg = "#676E7D"
info_fg = "#f3f4f5"

good_bg = "#576075"
good_fg = "#f3f4f5"

warning_bg = "#440a09"
warning_fg = "#f3f4f5"

critical_bg = "#E53935" 
critical_fg =  "#f3f4f5" 

[[block]]
block = "disk_space"
path = "/"
alias = "/ : "
info_type = "available"
unit = "GB"
interval = 20
warning = 100.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
